// src/pages/sitemap.xml.js
export default function Sitemap() {
    return null; // No rendering needed
}

export const getServerSideProps = async ({ res }) => {
    res.setHeader('Content-Type', 'application/xml');
    res.write(`<?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
     <url>
    <loc>https://ipractest.com/</loc>
    <lastmod>2024-04-20</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>

  <url>
    <loc>http://localhost:3000/Pages/AboutUs</loc>
      <lastmod>2024-03-12</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/Disclaimer</loc>
    <lastmod>2024-04-15</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/iPractest-Privacy-Policy</loc>
    <lastmod>2024-04-15</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
   <url>
    <loc>https://ipractest.com/iPractest-Terms-Conditions</loc>
    <lastmod>2024-04-15</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/iPractest-Deletion-Account-Policy</loc>
        <lastmod>2024-04-15</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
   <url>
    <loc>https://ipractest.com/ReadingPage/cambridgeAllTests</loc>
        <lastmod>2024-06-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/ReadingPage</loc>
           <lastmod>2024-06-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-1</loc>
           <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
       <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-2</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
       <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-3</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
       <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-4</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
       <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-5</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
       <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-6</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
       <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-7</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
       <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-8</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
       <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-9</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
       <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-10</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
       <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-11</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/cambridge-test-12</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-1</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-2</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-3</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-4</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-5</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-6</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-7</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-8</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-9</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-10</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-11</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ReadingPage/ReadingAllTests/Actual-Test-12</loc>
               <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/ListeningPage/cambridgeAllTests</loc>
               <lastmod>2023-10-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/ListeningPage</loc>
     <lastmod>2023-10-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
   <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-1</loc>
     <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
   <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-2</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-3</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-4</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-5</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-6</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-7</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-8</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-9</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-10</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-11</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Cambridge-test-12</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Actual-test-1</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Actual-test-2</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Actual-test-3</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Actual-test-4</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Actual-test-5</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Actual-test-6</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Actual-test-7</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/ListeningPage/ListeningAllTests/Actual-test-8</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>



 <url>
    <loc>https://ipractest.com/WrittingPage</loc>
         <lastmod>2024-06-25</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-1</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-2</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-3</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-4</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-5</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-6</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-7</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-8</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-9</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-10</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-11</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-12</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-13</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/WrittingPage/WritingAllTests/Actual-test-14</loc>
         <lastmod>2023-11-10</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>


  <url>
    <loc>https://ipractest.com/SpeakingPage</loc>
         <lastmod>2024-04-04</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test1Sec1</loc>
             <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test1Sec2</loc>
             <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test1Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test2Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test2Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test2Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>


  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test3Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test3Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test3Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>


  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test4Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test4Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test4Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test5Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test5Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test5Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test6Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test6Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test6Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test7Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test7Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test7Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>


  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test8Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test8Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test8Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test9Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test9Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test9Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test10Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test10Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test10Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test11Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test11Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test11Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test12Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test12Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test12Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test13Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test13Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test13Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test14Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test14Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test14Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test15Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test15Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test15Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test16Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test16Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test16Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test17Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test17Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test17Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test18Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test18Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test18Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test19Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test19Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test19Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test20Sec1</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test20Sec2</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
    <url>
    <loc>https://ipractest.com/SpeakingPage/AllTests/Test20Sec3</loc>
      <lastmod>2023-12-13</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>




   <url>
    <loc>https://ipractest.com/Speaking-user-Result-Page</loc>
      <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/paymentMethods</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/Payment-billing-information-page</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/React_SuccessURL/abc</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/React_FailedURL/abc</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/React_CancelURL/abc</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/Paypal</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/sop-download</loc>
     <lastmod>2024-02-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/SOP-Maker-for-user</loc>
     <lastmod>2024-02-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/lor-download</loc>
     <lastmod>2024-02-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/lor-Maker-for-user</loc>
     <lastmod>2024-01-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/Create-CV</loc>
     <lastmod>2024-01-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/Ipractest-Refund-Policy</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/Ipractest-Cencel-Policy</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/Ipractest-Forget-password-component</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/MainDashBoard/Dashboard</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/MainDashBoard/LeaderBoard</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/MainDashBoard/Speaking-Records</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/MainDashBoard/Let's-Practice</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/MainDashBoard/SOPFile</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/MainDashBoard/Referrals</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/justForTest</loc>
     <lastmod>2024-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
     <url>
    <loc>https://ipractest.com/error</loc>
     <lastmod>2023-07-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://ipractest.com/*</loc>
     <lastmod>2023-05-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>

    </urlset>`);
    res.end();
    return { props: {} }; // Return empty props
};
